# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qbCGTS8FPunc14KZ1ySSwiKZZmV-5GLK
"""

import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

def generate_data():
    celsius = np.linspace(-100, 100, num=500)  # Celsius values from -100 to 100
    fahrenheit = (9/5) * celsius + 32
    return celsius, fahrenheit

celsius, fahrenheit = generate_data()

model = keras.Sequential([
    layers.Dense(units=1, input_shape=[1])
])

model.compile(optimizer='adam', loss='mean_squared_error')

history = model.fit(celsius, fahrenheit, epochs=5000, verbose=0)

test_values = np.array([0, 10, 25, 100, -40], dtype=float)
predicted_fahrenheit = model.predict(test_values)

for i, c in enumerate(test_values):
    print(f"Celsius: {c} -> Predicted Fahrenheit: {predicted_fahrenheit[i][0]:.2f} (Actual: {(9/5)*c + 32:.2f})")